env_config:
  use_container: True
  env_id: "motion_control_continuous_laser-v0"
  seed: 14
  stack_frame: 1   # span 1, 4, 8
  kwargs:
    world_name: "world_0.world"
    gui: false
    verbose: false
    max_step: 400
    time_step: 0.2
    slack_reward: 0
    collision_reward: -1
    failure_reward: 0
    success_reward: 20
    goal_reward: 1
    max_collision: 1
    init_position: [-2, 3, 1.57]
    goal_position: [0, 10, 0]

    laser_clip: 5
    min_v: -1
    max_v: 2
    min_w: -3.14
    max_w: 3.14

training_config:
  algorithm: "TD3"
  encoder: "cnn"  # span "mlp", "cnn", "rnn", "transformer"
  buffer_size: 200000
  actor_lr: 0.00001
  critic_lr: 0.00002
  # For head
  num_layers: 1
  hidden_layer_size: 512
  # For encoder
  encoder_num_layers: 2
  encoder_hidden_layer_size: 512
  exploration_noise_start: 0.1
  exploration_noise_end: 0.0999
  pre_collect: 4096
  log_intervals: 2

  policy_args:
    tau: 0.005
    gamma: 0.99
    policy_noise: 0.2
    update_actor_freq: 2
    noise_clip: 0.5
    n_step: 4

  training_args:
    max_step: 4000000
    collect_per_step: 4096
    update_per_step: 1024
    batch_size: 128

container_config:
  # 5 container running in parallel
  num_actor: 5
  # 50 training dynamic-wall worlds
  worlds: [500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549]
  # 50 test dynamic-wall worlds
  test_worlds: [550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599]